### ISSUE TITLE
Finish the Title and Header classes

### ISSUE THREAD

**Issue by InACommandBlock** [McLow27/planetGame#2]
To finish the title screen, we still have to
- [x] Add hover animations for the buttons
- [x] Fix these diagonal lines in the title animation
- [x] Add the key listener actions

### Button hover actions
There are three options I can think of,
1. Increase the font size
2. Resize the button except this would require also relocating it accordingly
3. Changing the colour gradient of the button

@McLow27 you might wanna do this?

### Diagonal lines issue
I am pretty certain that this is an issue with the header bits being drawn incorrectly. In the constructor of the obj/Header class, this code should draw the part of the header this bit represents and then remove the upper left and lower right edges to make it a parallelogram.
```java
Graphics2D g = (Graphics2D) (b == 1 ? fr : bc).createGraphics();
g.drawImage(b == 1 ? this.front : this.back, -ln, -lnsum, null);
g.setComposite(AlphaComposite.getInstance(AlphaComposite.CLEAR));
g.drawPolygon(new int[] {0, width, 0}, new int[] {-1, -1, width-1}, 3);
g.drawPolygon(new int[] {0, width, width}, new int[] {height + width+1, height + width+1, height+1}, 3);
g.dispose();
```

### Keylistener actions
This one should be really easy; just create new classes for all the tabs there are (search; lobby; credits; settings; tutorial), keep in mind they must extend the GUI abstract class, and then configure the setUI method of the Engine class to show and tick these GUIs. And finally, of course, call the function with the required arguments from the keyPressed action listener method in gui/Title. _Please hold off on this until everything else is working properly though._

**Let's get to work!**

**Comment by InACommandBlock** [comment]
I think I fixed issue number two and BTW you can now replay the animation by pressing F5

**Comment by InACommandBlock** [comment]
@McLow27 Please close this issue, I don't think I have the ability to

**Comment by McLow27** [comment]
Perfect! Please assign some tasks for me for today or tomorrow.
